### ISSUE TITLE
T32 Kumottavien tietojen vienti/tuonti Ryhtiin

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/arho-backend#158]
Paikkatietoasiantuntijana haluan viedä kaavatiedot Ryhti-järjestelmään myös, jos kaava on hylätty, kumottu tai siitä on valitettu, koska muuten Ryhti-järjestelmässä ei ole tätä tietoa, jotta loppukäyttäjällä on saatavilla oikea tilanne.

Paikkatietoasiantuntijana haluan pitää huolta siitä, että kumottujen tietojen kohdalla tiedot päivitetään erikseen.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/236
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/171
- [ ] Ryhti-rajapintalisäosan pitäisi tehdä tämä, hakea tiedot Ryhdistä ja kumota halutut kohteet
```
